### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by stevie-mayhew** [guru-digital/SSAutoGitIgnore#1]
Would you mind tagging a release for this? (even 0.0.1)

It helps to speed up composer installs and hopefully mitigates any changes that would be made in the future.

Awesome module by the way!

**Comment by cjsewell** [comment]
Thanks for the feedback!

Done https://github.com/guru-digital/SSAutoGitIgnore/releases/tag/0.0.1

**Comment by stevie-mayhew** [comment]
Thanks heaps @cjsewell
