### ISSUE TITLE
Found end marker on line x without a start marker. Please manually edit

### ISSUE THREAD

**Issue by cjsewell** [guru-digital/SSAutoGitIgnore#3]
This was introduced by #2 Since the start marker has changed since the first release it is unable to find the Start marker.

To fix, edit your gitignore and remove all SSAutoGitIgnore related lines. Then rerun SSAutoGitIgnore, by either running
```
composer update
```
or
```
composer run-script post-update-cmd
```

**Comment by dhensby** [comment]
I think this is resolved?

**Comment by cjsewell** [comment]
Indeed!
